on: push
name: Check for syntax errors
jobs:
  check-for-syntax-errors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cclauss/Find-Python-syntax-errors-action@master
